# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:5.2.1-jdk8

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  APP_NAME: 'sequencetools'
  APP_VERSION: "2.33.4"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs=-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"

stages:
  - build
  - test
  - deploy
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
build:
  stage: build
  script:
    - chmod u+x gradlew
    - ./gradlew clean build --info -x test
  tags:
    - ena-dcap-gitlab-runner
  artifacts:
    paths:
      - build/libs/${APP_NAME}-${APP_VERSION}.jar

test:
  stage: test
  script:
    - chmod u+x gradlew
    - gradle test --info
  tags:
    - ena-dcap-gitlab-runner
  dependencies:
    - build
  allow_failure: true

publish:
  stage: deploy
  needs:
    - job: build
      artifacts: true
  script:
    - chmod u+x gradlew
    - ./gradlew publish
  tags:
    - ena-dcap-gitlab-runner
  when: manual
