/*
 * Copyright 2019-2024 EMBL - European Bioinformatics Institute
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License. You may obtain a copy of the License at
 * http://www.apache.org/licenses/LICENSE-2.0
 * Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 * CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 */
package uk.ac.ebi.embl.api.entry.sequence;

/** @author simonk */
public interface Sequences {

  String SEQ1 = "aaat";

  String SEQ2 =
      "acaatggcacatgaaatattgattgctgaagcagaggcatttctaaaaaatgttgctcct"
          + "gagaccaggacagcaataatttcagcaataacaggagggaaatcagcctgcaaatcagca"
          + "gctaaactgattaagaatgaacatcttcccctaatgtctggagaagccaccacaatgcac"
          + "atcgttatgaggtgcttatatcctgaaataaaaccatggaaaaaggcaagcgacatgctg"
          + "aataaagcaacttctagtttgaaaaaatcagaaggaagagacatcagaaagcaaatgaaa"
          + "gcagctggagacttcttaggagtggagtcaatgatgaaaatgagggcctttagagatgac"
          + "caaataatggaaatggttgaagaagtatatgatcacccagacgactacacaccagacatc"
          + "cgaataggaacaatcacagcttggttgagatgcaagaacaagaaaagtgaaagatacagg"
          + "agtaatgtctcagaaagtggaagaacagctttaaagattcatgaagtaagaaaagccagc"
          + "acagcaatgaacgaaattgctggtattactggccttggagaagaagcactatctctccaa"
          + "agacaaacagaaagtttggccatattatgtaatcacacttttggaagtaatataatgaga"
          + "ccccacttggaaaaagcaataaaaggagttgaaggcagagttggagagatgggacgaatg"
          + "gcaatgaaatggttagttgttataatatatttctctataacaagtcaacctgcttctgct"
          + "tgcaatctaaagacctgtctaaaactatttaacaatactgatgcggtaactgttcattgt"
          + "tttaatgaaaaccaaggatacatgctaacattagcctctttgggattagggataattact"
          + "atgttgtatttattagtaaaaatcataattgaacttgtcaatggttttgtgctcggcaga"
          + "tgggagagatggtgtggagatataaagaccacaattatgcctgaaattgactcgatggaa"
          + "aaagatattgccctctttagggagagacttgacctgggagaaggtgcccctgacgaaacc"
          + "gacaactcaccaattcctttttccaatgatggtatttttgaaatttaattaccttg";

  String SEQ3 =
      "atggcacatgaaatattgattgctgaagcagaggcatttctaaaaaatgttgctcctgag"
          + "accaggacagcaataatttcagcaataacaggagggaaatcagcctgcaaatcagcagct"
          + "aaactgattaagaatgaacatcttcccctaatgtctggagaagccaccacaatgcacatc"
          + "gttatgaggtgcttatatcctgaaataaaaccatggaaaaaggcaagcgacatgctgaat"
          + "aaagcaacttctagtttgaaaaaatcagaaggaagagacatcagaaagcaaatgaaagca"
          + "gctggagacttcttaggagtggagtcaatgatgaaaatgagggcctttagagatgaccaa"
          + "ataatggaaatggttgaagaagtatatgatcacccagacgactacacaccagacatccga"
          + "ataggaacaatcacagcttggttgagatgcaagaacaagaaaagtgaaagatacaggagt"
          + "aatgtctcagaaagtggaagaacagctttaaagattcatgaagtaagaaaagccagcaca"
          + "gcaatgaacgaaattgctggtattactggccttggagaagaagcactatctctccaaaga"
          + "caaacagaaagtttggccatattatgtaatcacacttttggaagtaatataatgagaccc"
          + "cacttggaaaaagcaataaaaggagttgaaggcagagttggagagatgggacgaatggca"
          + "atgaaatga";

  String SEQ4 =
      "atggctggtggtttgtcccaactcgttgcgtatggcgcacaagacgtgtacctgaccggt"
          + "aacccccagattaccttcttcaagactgtataccgccgctacaccaacttcgccattgaa"
          + "tcaatccaacaaacgatcaatggcagcgttggttttggcaacaaagtgagcacccagatc"
          + "tcccgtaacggtgacttgatcaccgacattgtggttgagttcgtgctgaccaagggtggc"
          + "aacggtggtaccacctactaccccgctgaggagctgctacaggatgttgagctcgaaatc"
          + "ggtggccagcgcattgacaagcactacaacgactggttccgcacctacgacgctctgttc"
          + "cgcatgaacgacgaccgttacaactaccgtcgtatgaccgactgggtcaacaacgaactt"
          + "gtcggtgcccagaagcgtttctacgtgcccctcatcttcttcttcaaccagacccctggt"
          + "cttgccctccccctaattgcctgcaatacccacgaagtgaagctttacttcaccctggca"
          + "agccaggtgcagggtgtgaactacaacggcagcagtgccatcgccggtgccgcccagcct"
          + "actatgtccgtgtgggttgactacatcttcctggatacccaagaacgcacccgtttcgcc"
          + "cagctaccccacgagtacctgatcgaacagctacagttcactggttccgagaccgccacc"
          + "ccctccgccaccacccaggccagccaaaacatccgcctcaacttcaaccaccccaccaag"
          + "tacctggcatggaacttcaacaaccccaccaactatggtcaatacactgctctggctaac"
          + "gttcccggtggttgctccggtgccggtactgccgccgctaccgtgaccatccccgactac"
          + "ggtaacactggcacctacaacgaacagctcgccgtgctggactctgccaagatccagctg"
          + "aacggtcaagatcgtttcgccacccgcaagggctcttacttcaacaaggtgcaaccttac"
          + "cagagcattggtggcgtcacccccgccggtgtctacctgtactccttcgccctgaaaccc"
          + "gctggtcgccaaccctccggtacctgcaacttctcccgcatcgataacgccactctgtct"
          + "ctgacttacaagacttgcagcgttgatgccacttcccctgccgcagtactcggcaacacc"
          + "gaaactgtgactgccaacaccgccactctcctaactgccctcaacatctacgctaaaaat"
          + "tttggcgggaaaagcatcacgccatgcacatctggacactgtgcatgggaaactcgtttg"
          + "gacttccagatgccaactatggcatatgtcagttgctagtaatctttttagattgcaaca"
          + "tcatcaaattgcgggaatccccttagagctcaaagtaccaaggatgattacgaaagtttc"
          + "atctggccaagaacagaccttgggtatggtaaaaatctttgagattgggcaatccgcagc"
          + "caagctcctaacaaactttagtttcacggagaaggttcaacgactaaatggtgatgggtc"
          + "tcttagaggcttaagatatagtctagtccctgagacatgagatctcattaaatatcccga"
          + "aaggagggtagaatcgaaaaattacaacgtccttcgcataatgagtggaatgggaggctt"
          + "ggcttatgccaactga";

  String SEQ5 =
      "atggctggtggtttgtcccaactcgttgcgtatggcgcacaagacgtgtacctgaccggt"
          + "aacccccagattaccttcttcaagactgtataccgccgctacaccaacttcgccattgaa"
          + "tcaatccaacaaacgatcaatggcagcgttggttttggcaacaaagtgagcacccagatc"
          + "tcccgtaacggtgacttgatcaccgacattgtggttgagttcgtgctgaccaagggtggc"
          + "aacggtggtaccacctactaccccgctgaggagctgctacaggatgttgagctcgaaatc"
          + "ggtggccagcgcattgacaagcactacaacgactggttccgcacctacgacgctctgttc"
          + "cgcatgaacgacgaccgttacaactaccgtcgtatgaccgactgggtcaacaacgaactt"
          + "gtcggtgcccagaagcgtttctacgtgcccctcatcttcttcttcaaccagacccctggt"
          + "cttgccctccccctaattgcctgcaatacccacgaagtgaagctttacttcaccctggca"
          + "agccaggtgcagggtgtgaactacaacggcagcagtgccatcgccggtgccgcccagcct"
          + "actatgtccgtgtgggttgactacatcttcctggatacccaagaacgcacccgtttcgcc"
          + "cagctaccccacgagtacctgatcgaacagctacagttcactggttccgagaccgccacc"
          + "ccctccgccaccacccaggccagccaaaacatccgcctcaacttcaaccaccccaccaag"
          + "tacctggcatggaacttcaacaaccccaccaactatggtcaatacactgctctggctaac"
          + "gttcccggtggttgctccggtgccggtactgccgccgctaccgtgaccatccccgactac"
          + "ggtaacactggcacctacaacgaacagctcgccgtgctggactctgccaagatccagctg"
          + "aacggtcaagatcgtttcgccacccgcaagggctcttacttcaacaaggtgcaaccttac"
          + "cagagcattggtggcgtcacccccgccggtgtctacctgtactccttcgccctgaaaccc"
          + "gctggtcgccaaccctccggtacctgcaacttctcccgcatcgataacgccactctgtct"
          + "ctgacttacaagacttgcagcgttgatgccacttcccctgccgcagtactcggcaacacc"
          + "gaaactgtgactgccaacaccgccactctcctaactgccctcaacatctacgctaaaaat"
          + "tacaacgtccttcgcataatgagtggaatgggaggcttggcttatgccaactga";

  String SEQ6 =
      "atgggctcaagaatatctcccgccatggcagatggtagatcctcaagtatgtaggggaag"
          + "aaaagcgttcggtcgagatgtatgtggatatcatctcgtgaaagcccgttgccgttccac"
          + "agcatttatgaaaatgctacgcagacgctagtgaaatctcttgattttgcaacactgtca"
          + "aattgcgggaacccctaaagcttgtgataccaaatcatattggaaactgtatgatggccg"
          + "agagcggaactcgggtatggtaaaaattcacatagatatatgggcaatccgcagccaagc"
          + "tcctaaaatatccattgggatttcaaggagaaggttcaacgactaaacggcagtgggtct"
          + "agtgcttagcacaggcttaagatatagtctagtccctgagacatgagatctcaataaata"
          + "tcccgaaaggagggtatcaacgttaccaattatgtgtccagcggtctgtataacaactat"
          + "ctcgaaggtaaattcaaaacccccgaagattctgattaccgcgcattcctccaaaagaac"
          + "gcgagggaggttgaaaaaactgtcaacgctctcactgtatactacgtaaaaccccctgtg"
          + "atgccgaaggtgaaacttaatgtgaccggcgatgccaacgccaagttgactgccgctcct"
          + "gtggattacaaccagagaatcctggacaacagttacacagataccatgactaaattccaa"
          + "agggtgactcggtaa";

  String SEQ7 =
      "atgggctcaagaatatctcccgccatggcagatggtagatcctttaccaattatgtgtcc"
          + "agcggtctgtataacaactatctcgaaggtaaattcaaaacccccgaagattctgattac"
          + "cgcgcattcctccaaaagaacgcgagggaggttgaaaaaactgtcaacgctctcactgta"
          + "tactacgtaaaaccccctgtgatgccgaaggtgaaacttaatgtgaccggcgatgccaac"
          + "gccaagttgactgccgctcctgtggattacaaccagagaatcctggacaacagttacaca"
          + "gataccatgactaaattccaaagggtgactcggtaa";

  String SEQ8 =
      "acacaaagtcctgggcaaaagaaaagcaaaataaccaactatagattagccaaaaccttt"
          + "ttgtttaaacagttagtaatttataagttttaatttataagtttaaatttataagtttta"
          + "attcataacttaagatttaaaatttataatttataacatactaattaatcttaagtatat"
          + "tgtatttgatttagtagagtgtagcaaatatgtctatttcaataccagcaagtgaatatc"
          + "aaagtagcaagacttatagtcaactactcatgacttttagagacatggtctctgaagagc"
          + "aatatagagtaatcaaagaaagaatggttgaaaacaataagcattactatgctctagata"
          + "aattctcgcagggtgtttatgatataaaagacatgcagatattagttgcagacttgtcat"
          + "ggctttgtgcttttgataaatcttcagatcaaagaactagagaaacattggtaatgatta"
          + "gcaagtgtgttttagatattatgctgagcctgaaacctgaagtcagtcaaacaaaatgct"
          + "ttgtttgtgacaagaaatcaacatatgagactgataatttatcagttgctaggcttgatg"
          + "atgttagcaataggttctctggtggatctgtgcactacatggtgaagctcaaagaacatg"
          + "ataaggttggactcatgtcatatatacatgaactgaagaagattggagggtaccgtggtt"
          + "ggtacagagatggtggcaaactaagacatgaatatattgtctatactgatgcaaaaccca"
          + "taatgagagagaagtttgcaccagtctgctgagatgtaaaagagggtgaaggaatactag"
          + "taattgacagaaaaacctaaaaaaacataaaaaagacaaaaaacaaaaaaacaaaaaacg"
          + "cagaaaacaaaaaaacacaaaaagagaagaagaaaaacaacacaaaagccataagtggaa"
          + "ccaatgtaaaaatgatggagaaatatgagataaataaagggaagaaaggtaggtaaagat"
          + "aaaaggagtgaaaatatgccatttaaagaagtagtaataagagggaaaaacacattgata"
          + "ataaaaaaatgtttaaagtgaaatagcaaaatgtccttcgggacatatccgagatattgt"
          + "gcaccggattcacaccgaagtgtgactttcttttatctttaatgtctaaatttgattctt"
          + "tccttagttctttgtatgtcccaacatactgtgactcccacatttttttatgatatttcc"
          + "ctcttcctgatatttgttttattcccgtcacatagtttcttatgatttcaatctctccct"
          + "tctgatcactgaatcacaattcatgataactgctggcatcttgtggatagattcattcat"
          + "ttatttattgtttactttcccaatgagaattctagagacatacatgattacaacacttgc"
          + "agagactatgctggtctttgggttgtcttccacaaactcaattaagaatttgacaagtgg"
          + "ttgatctgatctaaactgcaccattccattctctatattgttcttatcggaggaaacttc"
          + "aattgtgtgttccctaaggcttgtttcacaaaccactcttctcactcctcttcctgttgt"
          + "catgttgcaattgactctaacatcactacttgtgtgggtgtacactgatatatgttttga"
          + "gaatttctgaaaccctaagccttcaacattaaacctgaatgatgatagatcctcacaagt"
          + "aagcaatccccaaccaattctctcactctcaatataaagattgattatggctcctccaat"
          + "caacctggaaacacccttaatactacacttcgatattgaaccaacaaaatcactttcatg"
          + "ctcttggaccaattcctttagtgttttgatctgtatggtgattggccacatttgatcagt"
          + "tgagatttgataaccaccaaacaaaggctctagatgttccagatcattgttagttgtatt"
          + "agttcctgtaagtttgctatctccactatctaccataatattagaagtgtgttcataaat"
          + "atgttggtacttgatttcacacttcttagataattcataggctgaatcgtggtcaggaca"
          + "ctgaagtgaaccgtaatggtcatcactcaagtcacccaagtcgttaaaattgactttaaa"
          + "caattcactaccacaccttacaaattttgtaggtaataaaactggagttgttgagtctaa"
          + "agtcattgtgtatccattgcctttataaactgaggaactaatctctgctatggtttgatt"
          + "tgtacccatagtgattaccaagacaatgtatggttggaattcttgacattcttctgctga"
          + "acatattaacttatctccactctcaaccttcattctctgccaatggctagatcttatgaa"
          + "aggaactccacaggaaaagacccccacattctcatacttgcaataatcatgatgtagata"
          + "ttgttcctcatcatcccagatgctctttggaggatttaagctacaatctggaccagtgaa"
          + "gcatttataatcatctcttgtaatgacatacttatactttctggtgtagtaaatcactct"
          + "tgagttacatctcatgctaatccctagaacacgtattttgagattagcatctttaaaaga"
          + "taaacatgtctcatcacctattgatctaaatttcaaatttatagttgtgactgatctgca"
          + "tgcataggaattgcaagtgctaagagaggttatgctatcaacaccatctctgcaagaacc"
          + "tagaacgaggggaagaaataccaaaataattccgactgttaaatatgaaccatctctcat"
          + "acgatacctagttggtaaagttttacccttaccagaatccacatccttgacgttctcatc"
          + "tgctagattgcttaattcatcctgtttcacccttactaactcatgagcattgtagtcaga"
          + "tctcctccttttcagtaatctgaaggggtttggtatcaatttctttataaacctaaagac"
          + "aaaatttgttggcactattatcaagtaatacttaataagccctattatggtgaaaattac"
          + "tgtgattatgatcagtgcaattcctgagtaaagaaaccagacaaatcctttattacaatc"
          + "ccaatgttttagtctcagccaaaaatccatcctatcatacattgaacaaatgtttgtcgc"
          + "ttcacacttcacactacgataaacatcattgaaagctacattcacaacatctgtgtatag"
          + "tggcagctgtcttgaagtacaatcagtaaattcaaattcagtgtggtctatccatagttt"
          + "gcagtttttctcagaacttgttagtataccatcaatgcacttcactattatcttagaatc"
          + "atattctccatttttgtgaacacacacttctaaggattcagcagaaagtataaactgatc"
          + "ataagtcccttttctcaaagatcttgagtccatatccttcgtatcaattggtgttgtctt"
          + "aatcgtcattttcacatgccttctcagtatccacctgttacactcattaatgaagatatc"
          + "atcaaccctgcgtatagatgttgatctcagtattacattgtcgctaaacttatccatctt"
          + "accacagcactttgtagtatctgttctacacaaaccagctgtgtttagtcctgttttctc"
          + "caaatagtatccagaagtatacctggctctggagcaaatagaaattccttcattacagtc"
          + "ataataattgcagctaaatgatgaagtgatcctatcaccttcatcatggtagataacttg"
          + "tgtgtacagagacttggtttcggatagctctagcaaagctagagcaaatgtgatcacaag"
          + "caaccccattcctatacaggaacaaatggtctattataaccaattaatgggtggtgaatg"
          + "tcactaatagaccactggttgttagttgtgaaaacaattctgattgaagttgaataaaaa"
          + "atcctcataaatgaaacaaataagcaagtataaaacaaaggtcttccttgactttaagaa"
          + "atgtgtttgttttacaaatatgcccagactttgtgt";

  String SEQ9 =
      "atggggttgcttgtgatcacatttgctctagctttgctagagctatccgaaaccaagtct"
          + "ctgtacacacaagttatctaccatgatgaaggtgataggatcacttcatcatttagctgc"
          + "aattattatgactgtaatgaaggaatttctatttgctccagagccaggtatacttctgga"
          + "tactatttggagaaaacaggactaaacacagctggtttgtgtagaacagatactacaaag"
          + "tgctgtggtaagatggataagtttagcgacaatgtaatactgagatcaacatctatacgc"
          + "agggttgatgatatcttcattaatgagtgtaacaggtggatactgagaaggcatgtgaaa"
          + "atgacgattaagacaacaccaattgatacgaaggatatggactcaagatctttgagaaaa"
          + "gggacttatgatcagtttatactttctgctgaatccttagaagtgtgtgttcacaaaaat"
          + "ggagaatatgattctaagataatagtgaagtgcattgatggtatactaacaagttctgag"
          + "aaaaactgcaaactatggatagaccacactgaatttgaatttactgattgtacttcaaga"
          + "cagctgccactatacacagatgttgtgaatgtagctttcaatgatgtttatcgtagtgtg"
          + "aagtgtgaagcgacaaacatttgttcaatgtatgataggatggatttttggctgagacta"
          + "aaacattgggattgtaataaaggatttgtctggtttctttactcaggaattgcactgatc"
          + "ataatcacagtaattttcaccataatagggcttattaagtattacttgataatagtgcca"
          + "acaaattttgtctttaggtttataaagaaattgataccaaaccccttcagattactgaaa"
          + "aggaggagatctgactacaatgctcatgagttagtaagggtgaaacaggatgaattaagc"
          + "aatctagcagatgagaacgtcaaggatgtggattctggtaagggtaaaactttaccaact"
          + "aggtatcgtatgagagatggttcatatttaacagtcggaattattttggtatttcttccc"
          + "ctcgttctaggttcttgcagagatggtgttgatagcataacctctcttagcacttgcaat"
          + "tcctatgcatgcagatcagtcacaactataaatttgaaatttagatcaataggtgatgag"
          + "acatgtttatcttttaaagatgctaatctcaaaatacgtgttctagggattagcatgaga"
          + "tgtaactcaagagtgatttactacaccagaaagtataagtatgtcattacaagagatgat"
          + "tataaatgcttcactggtccagattgtagcttaaatcctccaaagagcatctgggatgat"
          + "gaggaacaatatctacatcatgattattgcaagtatgagaatgtgggggtcttttcctgt"
          + "ggagttcctttcataagatctagccattggcagagaatgaaggttgagagtggagataag"
          + "ttaatatgttcagcagaagaatgtcaagaattccaaccatacattgtcttggtaatcact"
          + "atgggtacaaatcaaaccatagcagagattagttcctcagtttataaaggcaatggatac"
          + "acaatgactttagactcaacaactccagttttattacctacaaaatttgtaaggtgtggt"
          + "agtgaattgtttaaagtcaattttaacgacttgggtgacttgagtgatgaccattacggt"
          + "tcacttcagtgtcctgaccacgattcagcctatgaattatctaagaagtgtgaaatcaag"
          + "taccaacatatttatgaacacacttctaatattatggtagatagtggagatagcaaactt"
          + "acaggaactaatacaactaacaatgatctggaacatctagagcctttgtttggtggttat"
          + "caaatctcaactgatcaaatgtggccaatcaccatacagatcaaaacactaaaggaattg"
          + "gtccaagagcatgaaagtgattttgttggttcaatatcgaagtgtagtattaagggtgtt"
          + "tccaggttgattggaggagccataatcaatctttatattgagagtgagagaattggttgg"
          + "ggattgcttacttgtgaggatctatcatcattcaggtttaatgttgaaggcttagggttt"
          + "cagaaattctcaaaacatatatcagtgtacacccacacaagtagtgatgttagagtcaat"
          + "tgcaacatgacaacaggaagaggagtgagaagagtggtttgtgaaacaagccttagggaa"
          + "cacacaattgaagtttcctccgataagaacaatatagagaatggaatggtgcagtttaga"
          + "tcagatcaaccacttgtcaaattcttaattgagtttgtggaagacaacccaaagaccagc"
          + "atagtctctgcaagtgttgtaatcatgtatgtctctagaattctcattgggaaagtaaac"
          + "aataaataa";

  String SEQ10 =
      "gaattcaaattatcgcttttcgcaccgtgtagtttgtgatgcatcccttccccagtacct"
          + "tatcagcacggagtcgaaaggccgtacctccgggatacaccttagaaatgcggttgaaat"
          + "aactgaagcttcggcctcattgggtatactgcgaaacaccaattcttcaaccgctacatc"
          + "gtcacgtatatcctgcattatggggaatcgttttaaaatactaattctgggcgttctgcg"
          + "ctcgggcattatagtcgcaatgacgtgctttatgaacttgtattcgagaacttcgcatct"
          + "cgtttttggggggtgcaaagatcttaacaagctgtaattggacgcgagatccctgttcgc"
          + "atcgggcatatcagccggtctctcgtaatgatggccgcccgtgatctcaggattgcaaca"
          + "attcatcaacgacgaccggccacgctcgttatcgctcgctttaccgcagatagtgcccga"
          + "accctgcttcaatgtccctagatctattatctcttgcatggatttcagtgtgtgttcgca"
          + "atggaggtctgtttgacaccgaacgaagttagacaaaaacgtgaaatagtccatttttaa"
          + "cgccgccaaaacatctctgcagtagatagtcggcggaaatattctagtaaggtcgatgat"
          + "tatatcacatcccatcaatagcatgtctgtatctgaagataacacatacgcaaccgtttt"
          + "ggtgtgaaagaggttagcacagatatcgtccgcttccatcatggccacatcgacataagg"
          + "gtatcccatatagcgaatggtatccatgcagagcctatgtagaattttgggcgtatcaga"
          + "cttatcgctccatctgcgtggtcttttgggcttccgcgttcttttgttccgcgcttctcc"
          + "ggtatccgcattctcgcattcgtcgcgcgaacgtacttgcagcctcccagaacctcctcc"
          + "cctcgcgatgcgagtagctgctagcgcctttgctccataaagcgttttcccatacttcga"
          + "aaacccccggtccgatacaaacaccggataatacgaccgttggtgtaacaaacgcagcag"
          + "acagtataagcaccgcagcgtggcgaccgagttgtcgactccgtcgaccttaccagggta"
          + "aattttttccagcagtccatacataacattccataaatccacggcaatgggcgtcatagc"
          + "cccgccggatatcgaacccgaaatgtgacttctcactaatccgttcgcataggcgaagtg"
          + "catgcaaccgtacacgcccatggcaactttcggagtcgcagtgtaagagacacggggtaa"
          + "tacgaattttgaattttgggagtatctgtcaagtatattcaactcttgaataaccacgac";

  String SEQ11 =
      "atgggcgtgtacggttgcatgcacttcgcctatgcgaacggattagtgagaagtcacatt"
          + "tcgggttcgatatccggcggggctatgacgcccattgccgtggatttatggaatgttatg"
          + "tatggactgctggaaaaaatttaccctggtaaggtcgacggagtcgacaactcggtcgcc"
          + "acgctgcggtgcttatactgtctgctgcgtttgttacaccaacggtcgtattatccggtg"
          + "tttgtatcggaccgggggttttcgaagtatgggaaaacgctttatggagcaaaggcgcta"
          + "gcagctactcgcatcgcgaggggaggaggttctgggaggctgcaagtacgttcgcgcgac"
          + "gaatgcgagaatgcggataccggagaagcgcggaacaaaagaacgcggaagcccaaaaga"
          + "ccacgcagatggagcgataagtctgatacgcccaaaattctacataggctctgcatggat"
          + "accattcgctatatgggatacccttatgtcgatgtggccatgatggaagcggacgatatc"
          + "tgtgctaacctctttcacaccaaaacggttgcgtatgtgttatcttcagatacagacatg"
          + "ctattgatgggatgtgatataatcatcgaccttactagaatatttccgccgactatctac"
          + "tgcagagatgttttggcggcgttaaaaatggactatttcacgtttttgtctaacttcgtt"
          + "cggtgtcaaacagacctccattgcgaacacacactgaaatccatgcaagagataatagat"
          + "ctagggacattgaagcagggttcgggcactatctgcggtaaagcgagcgataacgagcgt"
          + "ggccggtcgtcgttgatgaattgttgcaatcctgagatcacgggcggccatcattacgag"
          + "agaccggctgatatgcccgatgcgaacagggatctcgcgtccaattacagcttgttaaga"
          + "tctttgcaccccccaaaaacgagatgcgaagttctcgaatacaagttcataaagcacgtc"
          + "attgcgactataatgcccgagcgcagaacgcccagaattagtattttaaaacgattcccc"
          + "ataatgcaggatatacgtgacgatgtagcggttgaagaattggtgtttcgcagtataccc"
          + "aatgaggccgaagcttcagttatttcaaccgcatttctaaggtgtatcccggaggtacgg"
          + "cctttcgactccgtgctgataaggtactggggaagggatgcatcacaaactacacggtgc"
          + "gaaaagcgataa";

  String SEQ12 =
      "gcctcggcctcctgtatatataaaaaaaagggaaggtagggaggagctggctaaaactgg"
          + "atggctgccagccaagcatgagctcatacctagggagccaaccagctggcagccagaggg"
          + "agccctggctgcatgccactggcagttatagtgaaacccctcccatagtccttaatcaca"
          + "agtaaacaaagcacaaggggaagtggaaagcagccaggagcatgttttgcgagccagagc"
          + "tgttttggcttgtcaccagctggccatggttcttcgccagctgtcacgtaaggcttctgt"
          + "gaaagttagtaaaacctggagtggaacaaaaaaaagagctcaaaggattttaattttttt"
          + "gttagaatttttgctggatttttgcacaggtgaagacagtgtagacgggaaaaaaagaca"
          + "gaaacacagtggtttgactgagcagaaatacagtgctttgcctgaaccaaaagctacata"
          + "ggtaagtaatgtttttttttgtgttttcaggttcatgggtgccgcagttgcacttttggg"
          + "ggacctagttgctactgtttctgaggctgctgctgccacaggattttcagtagctgaaat"
          + "tgctgctggagaggctgctgctactatagaagttgaaattgcatcccttgctactgtaga"
          + "ggggattacaagtacctctgaggctatagctgcaataggccttactcctgaaacatatgc"
          + "tgtaattactggagctccgggggctgtagctgggtttgctgcattggttcaaactgtaac"
          + "tggtggtagtgctattgctcagttgggatatagattttttgctgactgggatcataaagt"
          + "ttcaacagttgggctttttcagcagccagctatggctttacaattatttaatccagaaga"
          + "ctactatgatattttatttcctggagtgaatgcctttgttaacaatattcactatttaga"
          + "tcctagacattggggcccttctttgttctccacaatctcccaggctttttggaatcttgt"
          + "tagagatgatttgccatctttaacatctcaggaaattcagagaagaacccaaaaactatt"
          + "tgttgaaagtttagcaaggtttttggaagaaactacttgggcaatagttaattcaccagt"
          + "taacttatataattatatttcagactattattctagattgtctccagttaggccctctat"
          + "ggtaaggcaggttgcccaaagggagggaacctatatttcctttggccactcatataccca"
          + "aagtatagatgatgcagacagcattcaagaagttacccaaaggctagatttaaaaacccc"
          + "aaatgtgcaatctggtgaatttatagagaaaagtcttgcaccaggaggtgcaaatcaaag"
          + "atctgctcctcaatggatgttgcctttacttttagggttgtacgggactgtaacacctgc"
          + "tcttgaagcatatgaagatggccccaacaaaaagaaaaggagaaaggaaggaccccgtgc"
          + "aagttccaaaacttcttataagaggaggagtagaagtgctagaagttaaaactggggttg"
          + "actcaattacagaggtagaatgctttttaactccagaaatgggtgacccagatgagcatc"
          + "ttaggggttttagtaagtcaatttctatatcagatacatttgaaagtgactccccaaata"
          + "aggacatgcttccttgttacagtgtggccagaattccactgcccaatctaaatgaggatc"
          + "tgacctgtggaaatatactaatgtgggaggctgttaccttaaaaactgaggttatagggg"
          + "tgacaactttgatgaatgtgcactctaatggtcaagcaactcatgacaatggtgcaggaa"
          + "agccagtgcagggcaccagctttcattttttttctgttgggggggaggctttagaattac"
          + "agggggtggtttttaattacagaacaaagtacccagatggaacaatttttccaaagaatg"
          + "caacagtgcaatctcaagtaatgaacacagagcacaaggcgtacctagataagaacaagg"
          + "catatcctgttgaatgttgggttcctgatcccaccagaaatgaaaacacaagatattttg"
          + "ggacactaacaggaggagaaaatgttcctccagttcttcatataacaaacactgccacaa"
          + "cagtgctgcttgatgaatttggtgttgggccactttgcaaaggtgacaacttgtatttgt"
          + "cagctgttgatgtttgtggcatgtttactaacagatctggttcccagcagtggagaggac"
          + "tgtccagatattttaaggttcagctaagaaaaaggagggttaaaaacccctacccaattt"
          + "ctttccttcttactgatttaattaacagaaggacccctagagttgatgggcagcctatgt"
          + "atggcatggatgctcaggtagaggaggttagagtttttgaggggacagaggaacttccag"
          + "gggacccagacatgatgagatatgttgacagatatggacagttgcagacaaagatgctgt"
          + "aatcaaaggcctttattgtaatatgcagtacattttaataaagtataaccagctttactt"
          + "tactgttgcagttattttgggggaggggtttttggttttttgaaacattgaaagccttta"
          + "cagatgtgataagtgcagtgttcctgtgtgtctgcaccagaggcttctgagacctgggaa"
          + "gagcattgtgattgagattcagtgcttgatccatgtccagagtcttctgcttcagaatct"
          + "tcctctctaggaaagtcaagaatgggtctccccataccaacattagctttcatagtagaa"
          + "aatgtatacatgcttatttctaaatccagcctttctttccactgcacaatcctctcatga"
          + "atggcagctgcaaagtcagcaactggcctaaaccagattaaaagcaaaagcaaagtcatg"
          + "ccactttgcaaaatccttttttctagtaaatattcagagcagcttagtgattttcttagg"
          + "taggccttaggtctaaaatctatttgccttacaaatctggcttgtaaagttctaggcact"
          + "gaatattcattcatggttacaattccaggtggaaacacctgtgttcttttgttttggtgt"
          + "tttctctctaaattaactttcacacttccatctaagtaatctcttaggcaatcaaggttg"
          + "cttatgccatgccctgaaggtaaatcccttgactctgcaccagtgccttttacatcctca"
          + "aatacaaccataaactgatctatacccactcctaactcaaagtttaatctttctaatggc"
          + "atgttaacatttaatgactttcccccacagagatcaagtaaagctgcagctaaagtagtt"
          + "ttgccactgtctattggccccttgaatagccagtacctttttttgggaatgtttaataca"
          + "atgcattttaagaactcataaatgacagtgtccatttgaggcagcaaacaatgaatccag"
          + "gccaccccagccatatattgctctaaaacagcattgccatgtgccccaaaaattaagtcc"
          + "attttatcaagcaaaaaattaaacctttcaactaacatttcttctctggtcatatggata"
          + "ctgtcaaccctttgtttggctgctacggtatcaacagcctgctggcaaatgcttttttga"
          + "tttttgctatctgcaaaaatttgggcattataatagtgcttttcatgatggttaaagtga"
          + "tttggctgatcctttttttcacattttttgcattgcagtgggttttcctgaaagtctaag"
          + "tacatgcccataagcaagaaaacatcctcacacttgatgtccaaagcatactgtgtaact"
          + "aatttccatgaaacctgcttagtttcttctggttcttctgggttaaagtcatgctcctta"
          + "aggcccccctgaatactttcttccactactgcatatggctgtctacacaaggcactgtaa"
          + "aacaagtattccttattcacacctttacaaattaaaaaactaaaggtacatagtttttga"
          + "cagtagttattaattgctgaaactctgtgtctatgtggtgttaaaaaaaacaaaatatta"
          + "tgacccccaaaaccatgtctacttataaaggttacagagtatttttccataagtttctta"
          + "tataaaatttgagctttttctttagtggtatacacagcaaaagaagcaacagttctatta"
          + "ctaaacacagcttgactgaggaatgcatgcagatctacaggaaagtctttagggtcttct"
          + "accttttttttcttcttaggtggggtagagtgctgggatcctgtgttttcatcatcactg"
          + "gcaaacatttcttcatggcaaaacaggtcttcatcccacttctcattaaatgtattccac"
          + "caggattcccattcatctgttccataggttggcacctaagaacaaaaaattaagtttatt"
          + "gtaaaaaacaaaatgccctgcaaaacaaaaattgtggtttaccttaaagctttagatccc"
          + "tgtagggggtgtctccaagaaccttctcccagcaatgaagagcttcttgggttaagtcac"
          + "acccaaaccattgtctgaagcaatcaaagcaatagcaatctatccacacaagtgggctgc"
          + "ttcttaaaaattttctgtttctatgccttaattttagcatgcacattaaacagggacaat"
          + "gcactgaaggattagtggcacaattaggccattccttgcaataaagggtatcagaattag"
          + "gaggaaaatcacaaccaacctctgaactattccatgtaccaaaatcaggctgatgagcaa"
          + "cttttacaccttgttccatttttttatataaaaaattcattctcttcattttgtcttcgt"
          + "ccccacctttatcagggtgaagttctttgcattttttcagataagcttttctcatgacag"
          + "gaatgtttccccatgcagatctatcaaggcctaataaatccatgagctccatggattcct"
          + "ccctattcagcactttgtccatttttgctttttgtagcaaaaaattaaagcaaaaaaggg"
          + "aaaaacaagggaatttccctggcctcctaaaaagcctccacgcccttactacttctgagt"
          + "aagcttggaggcggaggcg";

  String SEQ13 =
      "atggacaaagtgctgaatagggaggaatccatggagctcatggatttattaggccttgat"
          + "agatctgcatggggaaacattcctgtcatgagaaaagcttatctgaaaaaatgcaaagaa"
          + "cttcaccctgataaaggtggggacgaagacaaaatgaagagaatgaattttttatataaa"
          + "aaaatggaacaaggtgtaaaagttgctcatcagcctgattttggtacatggaatagttca"
          + "gaggtgccaacctatggaacagatgaatgggaatcctggtggaatacatttaatgagaag"
          + "tgggatgaagacctgttttgccatgaagaaatgtttgccagtgatgatgaaaacacagga"
          + "tcccagcactctaccccacctaagaagaaaaaaaaggtagaagaccctaaagactttcct"
          + "gtagatctgcatgcattcctcagtcaagctgtgtttagtaatagaactgttgcttctttt"
          + "gctgtgtataccactaaagaaaaagctcaaattttatataagaaacttatggaaaaatac"
          + "tctgtaacctttataagtagacatggttttgggggtcataatattttgttttttttaaca"
          + "ccacatagacacagagtttcagcaattaataactactgtcaaaaactatgtacctttagt"
          + "tttttaatttgtaaaggtgtgaataaggaatacttgttttacagtgccttgtgtagacag"
          + "ccatatgcagtagtggaagaaagtattcaggggggccttaaggagcatgactttaaccca"
          + "gaagaaccagaagaaactaagcaggtttcatggaaattagttacacagtatgctttggac"
          + "atcaagtgtgaggatgttttcttgcttatgggcatgtacttagactttcaggaaaaccca"
          + "ctgcaatgcaaaaaatgtgaaaaaaaggatcagccaaatcactttaaccatcatgaaaag"
          + "cactattataatgcccaaatttttgcagatagcaaaaatcaaaaaagcatttgccagcag"
          + "gctgttgataccgtagcagccaaacaaagggttgacagtatccatatgaccagagaagaa"
          + "atgttagttgaaaggtttaattttttgcttgataaaatggacttaatttttggggcacat"
          + "ggcaatgctgttttagagcaatatatggctggggtggcctggattcattgtttgctgcct"
          + "caaatggacactgtcatttatgagttcttaaaatgcattgtattaaacattcccaaaaaa"
          + "aggtactggctattcaaggggccaatagacagtggcaaaactactttagctgcagcttta"
          + "cttgatctctgtgggggaaagtcattaaatgttaacatgccattagaaagattaaacttt"
          + "gagttaggagtgggtatagatcagtttatggttgtatttgaggatgtaaaaggcactggt"
          + "gcagagtcaagggatttaccttcagggcatggcataagcaaccttgattgcctaagagat"
          + "tacttagatggaagtgtgaaagttaatttagagagaaaacaccaaaacaaaagaacacag"
          + "gtgtttccacctggaattgtaaccatgaatgaatattcagtgcctagaactttacaagcc"
          + "agatttgtaaggcaaatagattttagacctaaggcctacctaagaaaatcactaagctgc"
          + "tctgaatatttactagaaaaaaggattttgcaaagtggcatgactttgcttttgctttta"
          + "atctggtttaggccagttgctgactttgcagctgccattcatgagaggattgtgcagtgg"
          + "aaagaaaggctggatttagaaataagcatgtatacattttctactatgaaagctaatgtt"
          + "ggtatggggagacccattcttgactttcctagagaggaagattctgaagcagaagactct"
          + "ggacatggatcaagcactgaatctcaatcacaatgctcttcccaggtctcagaagcctct"
          + "ggtgcagacacacaggaacactgcacttatcacatctgtaaaggctttcaatgtttcaaa"
          + "aaaccaaaaacccctcccccaaaataa";

  String SEQ14 = "acgtttggaccttgg";
}
